import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# Load data
path = "day.csv"
df = pd.read_csv(path)

# Main title for the Streamlit app
st.title("Bike-sharing Dataset Analysis")

# Sidebar to select analysis
analysis_option = st.sidebar.selectbox(
    "Select Analysis",
    ("Overview", "Season and Weather Analysis", "Day of the Week Analysis", "Monthly Analysis")
)

# Data Overview
st.write("### Backround")
st.write("""
<div style="text-align: justify;">
    Bike sharing systems are new generation of traditional bike rentals where whole process from membership,
    rental and return back has become automatic. Through these systems, user is able to easily rent
    a bike from a particular position and return back at another position. Currently, there are about
    over 500 bike-sharing programs around the world which is composed of over 500 thousands bicycles.
    Today, there exists great interest in these systems due to their important role in traffic, 
    environmental and health issues. Apart from interesting real world applications of bike sharing systems,
    the characteristics of data being generated by these systems make them attractive for the research. Opposed to other transport
    services such as bus or subway, the duration of travel, departure and arrival position is explicitly
    recorded in these systems. This feature turns bike sharing system into a virtual sensor network that 
    can be used for sensing mobility in the city. Hence, it is expected that most of important events in 
    the city could be detected via monitoring these data.
</div>
""", unsafe_allow_html=True)


st.write("### Business Questions")
st.text("""
    pertanyaan 1 : Apakah musim dan cuaca mempengaruhi penggunaan sepeda?
    pertanyaan 2 : Pada hari apakah penggunaan sepeda terbanyak? dan bagaimana segmentasi pasarnya?
    pertanyaan 3 : Selama 2 tahun ini (2011-2012) apakah pertumbuhan bisnis cenderung meningkat atau merendah?
    pertanyaan 4 : Segmentasi pengguna sepeda apa yang harus menjadi fokus pemasaran perusahaan?
""")

st.write("### Metode analisis: Association Analysis")
st.write("""
<div style="text-align: justify;">
        Dalam kasus ini kita bisa menerapkan analisis asosiasi untuk menemukan hubungan antara
        item atau elemen dalam data. Dimana telah ditemukan bahwa segmentasi pelanggan 
        berkaitan erat terhadap frekuensi penggunaan sepeda berdasarkan hari, tentu hal
        ini bisa menjadi celah penerapan pola bisnis baru untuk memaksimalkan temuan tersebut.
        Dan juga terdapat pola penggunaan berdasarkan bulan dan musim, dimana sekitar bulan 4-10 
        adalah kurva yang bagus dalam menyiapkan langkah-langkah bisnis yang efektif
</div>
""", unsafe_allow_html=True)



if analysis_option == "Overview":
    st.write("### Data Overview")
    st.write(df.head())
    st.write("Count number of records:", len(df))
    st.write("Number of duplicated records:", df.duplicated().sum())

# Season and Weather Analysis
if analysis_option == "Season and Weather Analysis":
    st.write("### Season and Weather Analysis")
    dfg1_piv = df.pivot_table(index="season", columns="weathersit", values='cnt', aggfunc='sum')
    st.write("Pivot Table:")
    st.write(dfg1_piv)
    st.write("Bar Plot:")
    st.bar_chart(dfg1_piv)

    st.write("### conclution pertanyaan 1")
    st.write("""
    <div style="text-align: justify;">
        Musim dan cuaca mempengaruhi penggunaan sepeda, dimana penggunaan terbanyak terdapat pada musim ke 3 
             (fall atau gugur) dan cuaca ke 1 (Clear, Few clouds, Partly cloudy, Partly cloudy) serta penggunaan
              paling sedikit atau tidak ada sama sekali terdapat pada semua musim dan cuaca ke 4 
             (Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog)
    </div>
    """, unsafe_allow_html=True)

# Day of the Week Analysis
if analysis_option == "Day of the Week Analysis":
    st.write("### Day of the Week Analysis")
    dfg2_casual = df.groupby('weekday')["casual"].sum()
    dfg2_registered = df.groupby('weekday')["registered"].sum()
    dfg2_cnt = df.groupby('weekday')["cnt"].sum()
    
    st.write("Casual Users by Day of the Week")
    st.line_chart(dfg2_casual)
    
    st.write("Registered Users by Day of the Week")
    st.line_chart(dfg2_registered)
    
    st.write("Count Users by Day of the Week")
    st.line_chart(dfg2_cnt)

    st.write("### conclution pertanyaan 2")
    st.write("""
    <div style="text-align: justify;">
            Jumlah penggunaan sepeda terhadap hari tidak terlalu berpengaruh secara signifikan, cenderung merata.
            Jumlah penggunaan tertinggi terdapat pada hari ke 5 (Friday) dan paling rendah hari ke 0 (minggu). 
            Namun jika dilihat berdasarkan segmentasi pelanggan maka bisa disimpulkan mayoritas pengguna terdaftar
            (registered) cenderung meningkat pada hari kerja atau weekday sedangkan untuk pengguna biasa (casual)
            cenderung meningkat pada hari-hari weekend
    </div>
    """, unsafe_allow_html=True)
   
    
# Monthly Analysis
if analysis_option == "Monthly Analysis":
    st.write("### Monthly Analysis")
    dfg3 = df.groupby(['mnth', 'yr'])["cnt"].sum().reset_index()
    dfg3_yr0 = dfg3[dfg3['yr'] == 0]
    dfg3_yr1 = dfg3[dfg3['yr'] == 1]
    
    st.write("Count Users Over 2 Years")
    st.write("Count:", dfg3['cnt'].sum())
    st.write("Count Users in 2011")
    st.write("Count:", dfg3_yr0['cnt'].sum())
    st.write("Count Users in 2012")
    st.write("Count:", dfg3_yr1['cnt'].sum())

    st.write("Count Users Over 2 Years")
    st.line_chart(dfg3.set_index('mnth'))
    st.write("Count Users in 2011")
    st.line_chart(dfg3_yr0.set_index('mnth'))
    st.write("Count Users in 2012")
    st.line_chart(dfg3_yr1.set_index('mnth'))

    st.write("### conclution pertanyaan 3")
    st.write("""
    <div style="text-align: justify;">
            Bisnis meningkat tiap tahunnya dari 2011 sampai 2012, namun untuk puncak penggunaan tertinggi berbeda tiap tahunnya. 
            1. Untuk 2011 pada bulan ke 6 atau juni (musim semi)
            2. Untuk 2012 pada bulan ke 9 atau juni (musim gugur)
            Hal ini berbanding lurus dengan kesimpulan pertanyaan ke 1, namun harus mempertimbangkan tingkat pertumbuhan berdasarkan tahun
    </div>
    """, unsafe_allow_html=True)